pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-e HOME=/tmp'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test -- --watchAll=false'
            }
        }
    }
}
