pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-e HOME=/tmp -p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'NODE_OPTIONS=--openssl-legacy-provider npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'NODE_OPTIONS=--openssl-legacy-provider npm test -- --watchAll=false'
            }
        }
        stage('Manual Approval') {
            steps {
                script {
                    input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'npm install -g serve'
                sh 'serve -s build -l 3000 & sleep 60; kill %1'
            }
        }
    }
}
